### ISSUE TITLE
Ausgabe von 'definition' fehlt

### ISSUE THREAD

**Issue by nichtich** [gbv/uri-gbv-terminology#13]
Anscheinend geht das Feld bei der JSKOS-Validierung verloren

**Comment by StiftungAusNachlass** [comment]
Wir könnten das jetzt ganz gut gebrauchen. :-)

**Comment by nichtich** [comment]
Kannst du bitte ein Beispiel eines vorhandenen Datensatz mit dem `definition` Feld zum Testen geben?

**Comment by StiftungAusNachlass** [comment]
Natürlich, sorry:
[http://api.dante.gbv.de/data?uri=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fdante%2Fbd847cc5-5583-4081-909f-37545090b77b&properties=+definition](http://api.dante.gbv.de/data?uri=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fdante%2Fbd847cc5-5583-4081-909f-37545090b77b&properties=+definition)

<pre><code>
[
    {
        "uri": "http:\/\/uri.gbv.de\/terminology\/gender\/bd847cc5-5583-4081-909f-37545090b77b",
        "type": [
            "http:\/\/www.w3.org\/2004\/02\/skos\/core#Concept"
        ],
        "@context": "http:\/\/gbv.github.io\/jskos\/context.json",
        "inScheme": [
            {
                "uri": "http:\/\/uri.gbv.de\/terminology\/gender\/",
                "prefLabel": {
                    "de": "Geschlecht"
                }
            }
        ],
        "publisher": [
            {
                "prefLabel": {
                    "de": "Verbundzentrale des GBV (VZG)"
                }
            }
        ],
        "license": [
            {
                "uri": "http:\/\/creativecommons.org\/publicdomain\/zero\/1.0\/",
                "notation": [
                    "CC0 1.0",
                    "CC0"
                ],
                "prefLabel": {
                    "de": "Creative Commons Public Domain Dedication",
                    "en": "Creative Commons Public Domain Dedication"
                }
            }
        ],
        "identifier": [
            "http:\/\/www.rdaregistry.info\/termList\/gender\/#1003",
            "http:\/\/d-nb.info\/standards\/vocab\/gnd\/gender#notKnown",
            "http:\/\/publications.europa.eu\/resource\/authority\/human-sex\/NKN"
        ],
        "prefLabel": {
            "en": "unknown gender",
            "de": "unbekannt"
        },
        "altLabel": {
            "de": [
                "unbekanntes Geschlecht"
            ]
        },
        "definition": {
            "de": [
                "Die Geschlechtskennzeichnung, wenn das spezifische Geschlecht unbekannt ist."
            ],
            "en": [
                "The gender designation when specific gender is unknown."
            ]
        },
        "narrower": []
    }
]</code></pre>

**Comment by nichtich** [comment]
Ist doch da (?): http://uri.gbv.de/terminology/gender/bd847cc5-5583-4081-909f-37545090b77b

**Comment by StiftungAusNachlass** [comment]
Hups! Oh, ja... Sorry, dann ist der issue wohl solved.. :-)
